from aws_cdk import (
    Duration,
    Stack,
    aws_rds as rds,
    aws_ec2 as ec2,
    aws_ssm as ssm
)
from constructs import Construct


class DatabaseStack(Stack):

    def __init__(
            self,
            scope: Construct,
            construct_id: str,
            vpc: ec2.Vpc,
            database_name: str,
            backup_retention_days: int = 1,
            **kwargs
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)
        self.vpc = vpc
        self.database_name = database_name
        self.backup_retention_days = backup_retention_days

        # Our network in the cloud
        self.rds = rds.DatabaseInstance(
            self,
            "RDS",
            engine=rds.DatabaseInstanceEngine.postgres(version=rds.PostgresEngineVersion.VER_16_4),
            vpc=self.vpc,
            vpc_subnets=ec2.SubnetSelection(
                subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS
            ),
            storage_encrypted=True,
            allocated_storage=10,
            database_name=self.database_name,
            backup_retention=Duration.days(
                self.backup_retention_days
            ),  # 1 day retention is free
            deletion_protection=True,
            # parameter_group=rds.ParameterGroup.from_parameter_group_name(  # Specify the postgresql version
            #     self,
            #     "AuroraDBParameterGroup",
            #     "default.aurora-postgresql10",  # Only this version is supported for Aurora Serverless now
            # ),
            instance_type=ec2.InstanceType("t4g.micro"),
        )
        # Allow ingress traffic from ECS tasks
        self.rds.connections.allow_default_port_from_any_ipv4(
            description="Services in private subnets can access the DB"
        )
        # Save the name of the autogenerated secrets manager secret holding database credentials
        self.ssm_db_secret_name_param = ssm.StringParameter(
            self,
            "DatabaseSecretNameParam",
            parameter_name=f"/{scope.stage_name}/DatabaseSecretNameParam",
            string_value=self.rds.secret.secret_name,
        )
